#Used: this site to create this yml file:
#https://levelup.gitconnected.com/creating-and-filling-a-postgres-db-with-docker-compose-e1607f6f882f
version: '3.7'
services:
    postgres:
        image: postgres:10.5
        restart: always
        environment: 
          - POSTGRES_USER=admin
          - POSTGRES_PASSWORD=root
          - POSTGRES_DB=signapay
          - POSTGRES_HOST=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes:
          # uncomment the line below to persist data
          #- ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables - not 100% sure if this works
          - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
